[mypy]
python_version = 3.13
warn_return_any = true
warn_unused_configs = true

[mypy-cassandra.*]
ignore_missing_imports = true

[mypy-plotly.*]
ignore_missing_imports = true

[mypy-streamlit.*]
ignore_missing_imports = true

[mypy-loguru.*]
ignore_missing_imports = true